site_name: Static Site MkDocs
site_url: https://w1ldfox.github.io/static-site-mkdocs/
site_description: Учебный проект по развертыванию статического сайта
site_author: W1ldFox

nav:
  - Главная: index.md
  - Вторая страница: second-page.md

theme:
  name: readthedocs
  language: ru